language: python
python:
  - 3.6

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install codacy-coverage

# command to run tests
script:
  - coverage run -m unittest discover -s test

  # Upload coverage data to codecov
  - codecov

  # Upload to codacy
  - coverage xml
  - python-codacy-coverage -r coverage.xml
