language: python
python:
  - 3.6

# Cache packages
cache: pip

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov

# command to run tests
script:
  - coverage run -m unittest discover -s test

  # Upload coverage data to codecov
  - codecov
